CREATE TABLE IF NOT EXISTS venuno_order_sync_audit (
  audit_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  batch_id VARCHAR(64) NOT NULL, mode VARCHAR(16) NOT NULL, magento_order_id INT UNSIGNED NOT NULL,
  source_order_entity_id VARCHAR(64) NOT NULL, increment_id VARCHAR(64) NOT NULL, legacy_updated_at VARCHAR(32) NOT NULL,
  payload_hash VARCHAR(64) NULL, categories TEXT NULL, changes MEDIUMTEXT NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'applied',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, rolled_back_at TIMESTAMP NULL,
  KEY VENUNO_ORDER_SYNC_AUDIT_BATCH_ID (batch_id), KEY VENUNO_ORDER_SYNC_AUDIT_MAGENTO_ORDER_ID (magento_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
